"""empty message

Revision ID: 104da81365d6
Revises: cf7a34c1fdac
Create Date: 2020-04-13 18:27:33.435927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '104da81365d6'
down_revision = 'cf7a34c1fdac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('section', sa.Column('photo_result', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('section', 'photo_result')
    # ### end Alembic commands ###
