"""empty message

Revision ID: ad478145554d
Revises: c98d3220c5f1
Create Date: 2020-03-27 22:09:22.396306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad478145554d'
down_revision = 'c98d3220c5f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('section',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('course_id', sa.String(), nullable=True),
    sa.Column('photo', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('count')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('section')
    # ### end Alembic commands ###
